# Please refer https://docs.docker.com/compose to learn more about Docker Compose.

# This is a sample docker-compose file with two services
# 1. yourwebapp is an sample web service where the docker container image will be built from the Dockerfile as
#    part of starting the compose.
# 2. redis is an existing image hosted in docker hub.
version: "3.4"

services:
  # yourwebapp:
  #   image: hueidou/wpd
  #   ports:
  #     - 80

  sqlite-web:
    image: coleifer/sqlite-web
    environment: 
      - SQLITE_DATABASE=wpd.db
    volumes:
      - /app/wpd/data/sqlite:/data
    ports:
      - 8080:8080
