// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebPlagiarismDetection.Models;

namespace WebPlagiarismDetection.Migrations
{
    [DbContext(typeof(WpdContext))]
    [Migration("20201107103112_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebPlagiarismDetection.Models.Sentence", b =>
                {
                    b.Property<Guid>("SentenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("No")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("WpdId")
                        .HasColumnType("char(36)");

                    b.HasKey("SentenceId");

                    b.ToTable("Sentences");
                });

            modelBuilder.Entity("WebPlagiarismDetection.Models.SentenceSearch", b =>
                {
                    b.Property<Guid>("SentenceSearchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("No")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SearchEngine")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("SentenceId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Text")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Url")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("SentenceSearchId");

                    b.ToTable("SentenceSearchs");
                });

            modelBuilder.Entity("WebPlagiarismDetection.Models.Wpd", b =>
                {
                    b.Property<Guid>("WpdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DetectBeginTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DetectEndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("File")
                        .HasColumnType("longblob");

                    b.Property<string>("Result")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Text")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("WpdId");

                    b.ToTable("Wpds");
                });
#pragma warning restore 612, 618
        }
    }
}
