---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Text Search Text"
host: "localhost:8080"
basePath: "/"
tags:
- name: "search"
  description: "Text search text"
schemes:
- "http"
paths:
  /search:
    post:
      tags:
      - "search"
      summary: "Text search text"
      operationId: "search"
      produces:
      - "applicaton/json"
      parameters:
      - name: "text"
        in: "formData"
        description: "文本"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/SearchResult"
        "400":
          description: "文本为空或其他参数问题"
      x-swagger-router-controller: "Search"

definitions:
  SearchResult:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Tag"
    example:
      name: "name"
      id: 1
